const toggle=document.querySelector(".menu-toggle"),links=document.querySelector(".nav-links");
if(toggle)toggle.addEventListener("click",()=>links.classList.toggle("open"));
document.querySelectorAll(".nav-links a").forEach(a=>a.addEventListener("click",()=>links.classList.remove("open")));
document.getElementById("year").textContent=new Date().getFullYear();
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
document.getElementById("evaluateBtn").addEventListener("click",()=>{const text=document.getElementById("response").value.trim();const words=text?text.split(/\s+/).length:0;const sentences=Math.max(1,(text.match(/[.!?]+/g)||[]).length);const avg=words/sentences;const clarity=clamp(.72+(avg<24?.16:avg<35?.08:.02)+(text.length>80?.04:0),0,.99);const relevance=clamp(.55+(Math.min(words,60)/60)*.35,0,.99);const reasoning=clamp(.58+(sentences>=2?.12:0)+(text.includes("because")||text.includes("therefore")?.12:0),0,.99);const factual=clamp(.70+(text.length>100?.12:0),0,.99);[["clarity",clarity],["relevance",relevance],["reasoning",reasoning],["factual",factual]].forEach(([id,v])=>{document.getElementById(id).textContent=v.toFixed(2);document.querySelector("#"+id).parentElement.querySelector("i").style.width=(v*100)+"%"})});
document.getElementById("optimizeBtn").addEventListener("click",()=>{const p=document.getElementById("prompt").value.trim();if(!p){document.getElementById("optimized").textContent="Enter a prompt first.";return}document.getElementById("optimized").textContent=`Act as an expert assistant. ${p.charAt(0).toUpperCase()+p.slice(1).replace(/[.?!]+$/,"")}. Provide a clear, accurate, well-structured response with relevant examples, practical details, and a concise conclusion.`});
const sales=[110,78,74,101,96,88,104,142,121,93,111,116],orders=[410,310,295,385,360,335,405,520,460,350,420,486],months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],chart=document.getElementById("chart");
function renderChart(){const sel=document.getElementById("month").value,values=sel==="all"?sales:[sales[Number(sel)]];chart.innerHTML="";const max=Math.max(...sales);values.forEach((v,i)=>{const idx=sel==="all"?i:Number(sel),bar=document.createElement("div");bar.className="bar";bar.style.height=(v/max*100)+"%";bar.title=months[idx]+" — $"+v+"k";chart.appendChild(bar)});if(sel==="all"){const total=sales.reduce((a,b)=>a+b,0),count=orders.reduce((a,b)=>a+b,0);document.getElementById("sales").textContent="$"+total.toFixed(0)+"K";document.getElementById("orders").textContent=count.toLocaleString();document.getElementById("avg").textContent="$"+Math.round(total*1000/count)}else{const i=Number(sel);document.getElementById("sales").textContent="$"+sales[i]+"K";document.getElementById("orders").textContent=orders[i].toLocaleString();document.getElementById("avg").textContent="$"+Math.round(sales[i]*1000/orders[i])}}
document.getElementById("month").addEventListener("change",renderChart);renderChart();